
[[sec-data-quality]]
== Data Quality
=== Introduction to data quality
Data quality allows users and user systems to assess fitness for use of the provided data. Data quality measures and the associated evaluation are reported as metadata of a data product. This metadata improves interoperability with other data products and provides usage by user groups that the data product was not originally intended for. The secondary users can make assessments of the data product usefulness in their application based on the reported data quality measures.

For {series}-{docnumber} the following Data Quality Elements have been included:

* Conformance to this Product Specification; 
* Intended purpose of the data product; 
* Completeness of the data product in terms of coverage; 
* Logical consistency; 
* Positional uncertainty and accuracy; 
* Thematic accuracy; 
* Temporal quality; 
* Aggregation measures; 
* Validation checks or conformance checks including:
** General tests for dataset integrity;
** Specific tests for a specific data model.

=== Completeness
The presence and absence of features is described by the data quality elements Completeness (including commission and omission). Completeness should only be used on the feature type level, describing whether the features in the universe of discourse are found in the data set or not. 

==== Commission

[EDITOR]
--
Choosed Option a1 -> fits to previous text.

Annex *&lt;X&gt;* -> must be replaced -> Is that S-158:102?
--

Commission is applicable for {series}-{docnumber}.

{series}-{docnumber} products must be tested with commission checks prior to release by the Data Producer. The Data Producer must review the check results and address any issues to ensure sufficient quality of the data products. The checks are listed in Annex  [.red]#*&lt;X&gt;*#. Data should only be published if it passes the test.

==== Omission

[EDITOR]
--
Choosed Option a1 -> fits to previous text.

Annex *&lt;X&gt;* -> must be replaced -> Is that S-158:102?
--

Omission is applicable for {series}-{docnumber}. 

{series}-{docnumber} products must be tested with omission checks prior to release by the Data Producer. The Data Producer must review the check results and address any issues to ensure sufficient quality of the data products. The checks are listed in Annex [.red]#*&lt;X&gt;*#. Data should only be published if it passes the test.

=== Logical consistency

==== Conceptual consistency

[EDITOR]
--
Choosed Option a1 -> fits to previous text.

Annex *&lt;X&gt;* -> must be replaced -> Is that S-158:102?
--

Conceptual Consistency is applicable for {series}-{docnumber} and follows the guidelines from <<iho-s100,part=1>>.

{series}-{docnumber} products must be tested with conceptual consistency checks prior to release by the Data Producer. The Data Producer must review the check results and address any issues to ensure sufficient quality of the data products. The checks are listed in Annex [.red]#*&lt;X&gt;*#. Data should only be published if it passes the test.

==== Domain consistency

[EDITOR]
--
Choosed Option a1 -> fits to previous text.

Annex *&lt;X&gt;* -> must be replaced -> Is that S-158:102?

What about the sentence: "Data Producers must verify that the dataset conforms to the S-102 Feature Catalogue and to <<annex-data-classification-and-encoding-guide>>." -> remove?
--

Domain consistency is applicable for {series}-{docnumber} and follows the guidelines from <<iho-s100,part=5>>.

{series}-{docnumber} products must be tested with domain consistency checks prior to release by the Data Producer. The Data Producer must review the check results and address any issues to ensure sufficient quality of the data products. The checks are listed in Annex [.red]#*&lt;X&gt;*#. Data should only be published if it passes the test.

==== Format Consistency

[EDITOR]
--
Choosed Option a1 -> fits to previous text.

Annex *&lt;X&gt;* -> must be replaced -> Is that S-158:102?

What about the sentence: "Data Producers must verify that the dataset conforms to <<sec-data-product-format-encoding>> of this Product Specification." -> remove?
--

Format Consistency is applicable for {series}-{docnumber} and follows the guidelines from <<iho-s100,part=10c>>.

{series}-{docnumber} products must be tested with format consistency checks prior to release by the Data Producer. The Data Producer must review the check results and address any issues to ensure sufficient quality of the data products. The checks are listed in Annex [.red]#*&lt;X&gt;*#. Data should only be published if it passes the test.

==== Topological consistency
Topological consistency isn’t applicable for {series}-{docnumber} which is a grid Product Specification without curves and geometric surfaces.

=== Positional uncertainty and accuracy

==== Absolute or external accuracy

===== Vertical position accuracy

[EDITOR]
--
Is applicable according to "Report on the Cross Check of DQ Chapters of Phase 1 and New Product Specification; clause 3.1"

Choosed Option 2 & 2a.1

Needs a review by the S-102PT if Option 2b.1 or 2b.2 is applicable instead Option 2a.1
--

Vertical position accuracy is applicable for {series}-{docnumber} and follows the guidelines from <<iho-s100,part=4c>>.

{series}-{docnumber} products must be tested with vertical position accuracy checks prior to release by the Data Producer. The Data Producer must review the check results and address any issues to ensure sufficient quality of the data products. The checks are listed in Annex [.red]#*&lt;X&gt;*#. Data should only be published if it passes the test.

===== Horizontal position accuracy

[EDITOR]
--
Not applicable according to "Report on the Cross Check of DQ Chapters of Phase 1 and New Product Specification; clause 3.1"
--

Horizontal position accuracy isn’t applicable for {series}-{docnumber} which is a Product Specification without objects that have a horizontal coordinative value associated. 

==== Relative or internal accuracy

[EDITOR]
--
Choosed Option 2b.1 -> Using old text.
--

The internal positional accuracy is defined as the precision of the location of each grid point within the {series}-{docnumber} grid. The position of each grid point within the grid is referenced by a row and column combination. The metadata for {series}-{docnumber} defines a gridded resolution along both the X and Y axis of the grid. This absolute position of a grid point within the spatial projection of the grid is calculated using the row/column and the X/Y resolution. In this case, the accuracy is controlled by the precision used in defining these resolutions.

==== Gridded data positional accuracy

[EDITOR]
--
Choosed Option 2 & 2a.1

Annex *&lt;X&gt;* -> must be replaced -> Is that S-158:102?

What about paragraph 4, 5 -> these are part of the template for option 2 -> Where to populate RMSErrorPlanimetry?
--

Gridded data positional accuracy is applicable for {series}-{docnumber} and follows the guidelines from <<iho-s100,part=4c>>. 

{series}-{docnumber} products must be tested with gridded data positional accuracy checks prior to release by the Data Producer. The Data Producer must review the check results and address any issues to ensure sufficient quality of the data products. The checks are listed in Annex [.red]#*&lt;X&gt;*#. Data should only be published if it passes the test.

Gridded data positional accuracy is defined by the precision of the positional reference used to specify its location within its spatial projection. These positional references are contained within the spatial metadata of the {series}-{docnumber} grid. Nodes within a grid have an absolute position. It is assumed that any horizontal errors are assimilated into the vertical uncertainty. The vertical values that are calculated for that position by the processes and procedures used by each Data Producer during the creation of the {series}-{docnumber} grid. Appropriate selection of both the origin reference points and positional resolution are important and are another factor in gridded data positional accuracy.

In terms of gridded data positional accuracy, {series}-{docnumber} products shall at least populate 
RMSErrorPlanimetry that indicates the radius of a circle around the given point, in which the true value lies 
with probability P.

Recommendations on thresholds for gridded data positional accuracy are as follows:

[align=center]
stem:["Maximum RMSE"_"horizontal" = (GSD)/6] +
stem:["Maximum RMSE"_"vertical" = (GSD)/3]

Where:

[align=center]
stem:[GSD = "Ground Sampling Distance"]

=== Thematic accuracy

==== Thematic classification correctness
For S-102 bathymetric grids there are two classifications of data values, which are land and water. There are two considerations for assessing classification correctness when using the grid. The first is that values given in the depth layer of the S-102 grid are based on the associated hydrographic office's chosen vertical datum. Should another value in relation to a different vertical datum be required, a series of correctors would need to be applied. Secondly, when considering the data values, the value stored in the uncertainty for a given grid point must be considered. This uncertainty value represents the magnitude of possible deviation in either direction from the data value and must be applied when assessing the classification correctness. The new value generated when applied may cause a change in the classification.

==== Non-quantitative attribute accuracy

[EDITOR]
--
Choosed Option 1

Not applicable according to "Report on the Cross Check of DQ Chapters of Phase 1 and New Product Specification; clause 3.1"

The new text is the replacement text of the old template
--

Non-quantitative attribute accuracy isn’t applicable for {series}-{docnumber} which is a Product Specification without objects that have a non-quantitative attribute value.


==== Quantitative attribute accuracy
As defined in <<iho-s100,part=4c>> the data quality for the depth coverage is also defined as a co-located optional coverage, which is the uncertainty. This value particularly refers to the vertical uncertainty at each grid point. The uncertainty coverage supports multiple definitions of vertical uncertainty.

See <<tab-codes-defining-how-bathy-depth-uncertainty-determined>>.

=== Temporal accuracy

Temporal accuracy, consistency, and validity of bathymetric grids are confined to elements of the vertical control processes. These aspects are addressed during the formulation and application of vertical control processes applied by the various hydrographic offices. Details of these processes will be included in the Lineage portion of the metadata defined in <<sec-metadata>> of this Product Specification.

=== Aggregation
Aggregation isn’t applicable for {series}-{docnumber} because there is no need to aggregated data quality results based on different data quality elements. 
